[package]
name = "core-multiple-3"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Release please multiple 3"

[dependencies]
prover-multiple-3.workspace = true
