[package]
name = "prover-multiple-1"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Release please multiple prover 1"

[dependencies]
prover-multiple-3.workspace = true
