[package]
name = "prover-multiple-2"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Release please multiple prover 2"
publish = false

[dependencies]
prover-multiple-3.workspace = true
