name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  release:
    uses: matter-labs/zksync-ci-common/.github/workflows/release-please.yaml@aba-release-please-support
    secrets:
      gh_token: ${{ secrets.RELEASE_TOKEN }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
    with:
      manifest: '.github/release-please/manifest.json' # Specify the path to the manifest file
      config: '.github/release-please/config.json'     # Specify the path to the configuration file
      update-cargo-lock: true                          # Update Cargo.lock file
      workspace-dirs: 'core prover zkstack'            # Specify the workspace directories for single PR repos
      publish-to-crates-io: false                      # Enable publishing to crates.io
      upgrade-dependencies: false                      # Upgrade workspace dependencies
